# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [22]:
weather_csv = "Output/weather_data.csv"
weather_pd = pd.read_csv(weather_csv)
weather_pd.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,butaritari,100,KI,1578104981,74,3.07,172.79,28.89,3.58
1,qaanaaq,100,GL,1578104982,97,77.48,-69.36,-40.20,2.49
2,petropavlovsk-kamchatskiy,75,RU,1578104984,85,53.05,158.65,-10.00,4.00
3,saskylakh,98,RU,1578104985,97,71.97,114.09,-27.33,2.71
4,thompson,75,CA,1578104986,84,55.74,-97.86,-14.00,2.60

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [24]:
#Narrow down the cities to fit weather conditions. (wind speed >= 10)
weather_pd = weather_pd[weather_pd['Wind Speed']>=10]
weather_pd.shape

(19, 9)

In [17]:
gmaps.configure(api_key=g_key)

locations = weather_pd[["Lat", "Lng"]]
humidity = weather_pd["Humidity"].astype(float)

fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 )
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [27]:
weather_pd["Hotel Name"] = ""
weather_pd

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
9,hobart,93,AU,1578104913,38,-42.88,147.33,24.00,12.30,
53,new norfolk,36,AU,1578105038,38,-42.78,147.06,24.00,12.30,
110,narsaq,100,GL,1578105099,31,60.91,-46.05,2.00,19.00,
131,maple creek,83,CA,1578105121,55,49.91,-109.46,6.99,13.27,
137,sorland,100,NO,1578105128,83,67.67,12.69,0.68,20.50,
159,vestmannaeyjar,100,IS,1578105151,71,63.44,-20.27,1.05,16.68,
212,torbay,75,CA,1578105208,86,47.66,-52.73,-0.56,10.80,
222,cidreira,9,BR,1578105218,78,-30.17,-50.22,22.81,11.18,
259,qaqortoq,100,GL,1578105257,31,60.72,-46.03,2.00,19.00,
278,kaitangata,92,NZ,1578105278,72,-46.28,169.85,10.14,15.44,
358,hovd,75,NO,1578105363,93,63.83,10.70,4.00,14.90,
402,port pirie,19,AU,1578105410,58,-33.18,138.01,23.57,11.63,
414,margate,93,AU,1578105423,38,-43.03,147.26,24.00,12.30,
427,dunedin,73,NZ,1578105402,44,-45.87,170.50,14.44,13.86,
471,roald,100,NO,1578105483,80,62.58,6.12,3.33,10.30,
478,gravdal,100,NO,1578105460,74,59.79,5.78,3.00,11.80,
479,waingapu,87,ID,1578105492,78,-9.65,120.26,28.85,11.37,
491,brattvag,100,NO,1578105504,80,62.60,6.44,3.33,10.30,
500,palana,100,RU,1578105514,67,59.08,159.95,-4.53,14.22,

In [30]:
params = {
    "radius": 5000,
    "types": "hotel",
    "keyword": "hotel",
    "key": g_key
}

for index, row in weather_pd.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
#     print(name_address.url)

    # convert to json
    name_address = name_address.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        weather_pd.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

In [39]:
weather_pd

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
9,hobart,93,AU,1578104913,38,-42.88,147.33,24.00,12.30,Hotel Grand Chancellor Hobart
53,new norfolk,36,AU,1578105038,38,-42.78,147.06,24.00,12.30,The Woodbridge
110,narsaq,100,GL,1578105099,31,60.91,-46.05,2.00,19.00,Hotel Narsaq
131,maple creek,83,CA,1578105121,55,49.91,-109.46,6.99,13.27,Cobble Creek Lodge
137,sorland,100,NO,1578105128,83,67.67,12.69,0.68,20.50,Lofoten Værøy Brygge
159,vestmannaeyjar,100,IS,1578105151,71,63.44,-20.27,1.05,16.68,Hotel Vestmannaeyjar
212,torbay,75,CA,1578105208,86,47.66,-52.73,-0.56,10.80,Best Western Plus St. John's Airport Hotel and...
222,cidreira,9,BR,1578105218,78,-30.17,-50.22,22.81,11.18,Hotel Castelo
259,qaqortoq,100,GL,1578105257,31,60.72,-46.03,2.00,19.00,Hotel Qaqortoq
278,kaitangata,92,NZ,1578105278,72,-46.28,169.85,10.14,15.44,
358,hovd,75,NO,1578105363,93,63.83,10.70,4.00,14.90,
402,port pirie,19,AU,1578105410,58,-33.18,138.01,23.57,11.63,Ellen Hotel
414,margate,93,AU,1578105423,38,-43.03,147.26,24.00,12.30,Villa Howden
427,dunedin,73,NZ,1578105402,44,-45.87,170.50,14.44,13.86,Distinction Dunedin Hotel
471,roald,100,NO,1578105483,80,62.58,6.12,3.33,10.30,Vestavind Hytter og Rom AS
478,gravdal,100,NO,1578105460,74,59.79,5.78,3.00,11.80,Jarand Vikør Skarveland
479,waingapu,87,ID,1578105492,78,-9.65,120.26,28.85,11.37,Padadita Beach Hotel
491,brattvag,100,NO,1578105504,80,62.60,6.44,3.33,10.30,Brattvåg Fjordhotell
500,palana,100,RU,1578105514,67,59.08,159.95,-4.53,14.22,

In [50]:
narrowed_city_df = weather_pd
hotel_df = weather_pd[["City", "Country", "Lat", "Lng", "Hotel Name"]].copy()
hotel_df.dropna(subset=['Hotel Name'], inplace=True)
hotel_df

,City,Country,Lat,Lng,Hotel Name
9,hobart,AU,-42.88,147.33,Hotel Grand Chancellor Hobart
53,new norfolk,AU,-42.78,147.06,The Woodbridge
110,narsaq,GL,60.91,-46.05,Hotel Narsaq
131,maple creek,CA,49.91,-109.46,Cobble Creek Lodge
137,sorland,NO,67.67,12.69,Lofoten Værøy Brygge
159,vestmannaeyjar,IS,63.44,-20.27,Hotel Vestmannaeyjar
212,torbay,CA,47.66,-52.73,Best Western Plus St. John's Airport Hotel and...
222,cidreira,BR,-30.17,-50.22,Hotel Castelo
259,qaqortoq,GL,60.72,-46.03,Hotel Qaqortoq
278,kaitangata,NZ,-46.28,169.85,
358,hovd,NO,63.83,10.70,
402,port pirie,AU,-33.18,138.01,Ellen Hotel
414,margate,AU,-43.03,147.26,Villa Howden
427,dunedin,NZ,-45.87,170.50,Distinction Dunedin Hotel
471,roald,NO,62.58,6.12,Vestavind Hytter og Rom AS
478,gravdal,NO,59.79,5.78,Jarand Vikør Skarveland
479,waingapu,ID,-9.65,120.26,Padadita Beach Hotel
491,brattvag,NO,62.60,6.44,Brattvåg Fjordhotell
500,palana,RU,59.08,159.95,

In [41]:
coordinates = hotel_df[["Lat", "Lng"]]

figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

markers = gmaps.marker_layer(coordinates)

fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi…

In [51]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [52]:
# Add marker layer ontop of heat map
fig.add_layer(heat_layer)

# Display Map
fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi…